[package]
name = "ada-client"
description = "A signal monitor and grpc client for GNU/Linux"
homepage = "https://hostmobility.com"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ada-client"
path = "src/main.rs"

[dependencies]
async-lock = "2.6.0"
tonic = { version = "0.8.1", features = ["tls"] }
prost = "0.11"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread", "fs", "io-std", "net"] }
#tokio = { version = "1", features = ["full"], optional = true }
#tokio = { version = "1", features = ["io-std", "net"], optional = true }
tokio-socketcan = "0.3.1"
futures = { version = "0.3.24" }
gpio-cdev = { version = "0.5.1", features = ["async-tokio"] }
serde = "1.0.144"
toml = "0.5.9"
indexmap = { version = "1.9.1", optional = true }
serde_derive = "1.0.144"
bitflags = "1.3.2"
libc = "0.2.132"
nix = "0.25.0"
async-std = "1.12.0"
rand = "0.8.5"
#reqwest = "0.11"
home = "0.5.3"
can-dbc = "5.0.0"
codegen = "0.2.0"
lazy_static = "1.4.0"

[dev-dependencies]
futures-util = "0.3.24"

[build-dependencies]
tonic-build = "0.8.0"
prost-build = "0.11"

[features]
default = []
preserve_order = ["indexmap"]
