uid = 14

[gpio]
chip = "/dev/gpiochip10"
lines = [5, 6, 7, 8, 9, 10]

[time]
sleep_min_s = 1
sleep_max_s = 36000 
heartbeat_m = 60

[server]
address = "hm.fps-gbg.net"
port = 50051

[position]
longitude = 12.00837022
latitude = 57.40446609

